refuse to load any modules if FPGA not loaded. No FPGA, no valid slave memory, will hang on access  On branch k414 	modified:   CARE/acq400_dspfs.init 	modified:   dmaengine.c 	modified:   init/acq420.init

diff --git a/CARE/acq400_dspfs.init b/CARE/acq400_dspfs.init
--- a/CARE/acq400_dspfs.init
+++ b/CARE/acq400_dspfs.init
@@ -1,5 +1,10 @@
 #!/bin/sh
 # dsp1.init : instantiate DSP1 fs.
+
+if [ ! -e /etc/sites ]; then
+	echo "ERROR: /etc/sites does not exist. FPGA not loaded, quit"
+	exit 1
+fi
 MDIR=/usr/local/lib/modules
 /sbin/insmod $MDIR/debugfs2.ko
 if [ -e /mnt/local/regfs.ko ]; then
diff --git a/init/acq420.init b/init/acq420.init
--- a/init/acq420.init
+++ b/init/acq420.init
@@ -661,6 +661,10 @@ echo "for debug:"
 echo "echo file acq400_drv.c +p" \> /sys/kernel/debug/dynamic_debug/control
 echo "echo file acq400_sysfs.c +p" \> /sys/kernel/debug/dynamic_debug/control
 
+if [ ! -e /etc/sites ]; then
+	echo "ERROR: /etc/sites does not exist. FPGA not loaded, quit"
+	exit 1
+fi
 source /etc/sites
 good_sites=${good_sites%*,C}
 if [ "x$good_sites" != "x" ]; then
