support STACK and STAGGER 	modified:   CARE/stack_480 	modified:   acq400.h 	modified:   acq400_drv.c 	modified:   acq400_sysfs.c 	modified:   init/acq420.init

diff --git a/CARE/stack_480 b/CARE/stack_480
--- a/CARE/stack_480
+++ b/CARE/stack_480
@@ -5,19 +5,33 @@
 STACK_MODE=/dev/shm/stack_mode
 
 set_stack_mode() 
-{
+{ 
+(
 	for s in $(echo $3 | tr , ' '); do
 		/usr/local/CARE/acq480_$2 $s
 	done
 	run0 $3
 	set.site 0 NCHAN $1
+) 1>&2
 }
 
+dk=/dev/acq400.0.knobs
+
+if [ -e ${dk}/has_axi_dma_stack ]; then
+    case $(cat ${dk}/has_axi_dma_stack) in
+    2) SITES=1,3;;
+    1) SITES=1,2;;
+    0)
+        echo "ERROR no stack"; exit 1;;
+    esac
+else
+    echo "ERROR no stack"; exit 1
+fi
 case $1 in
 2x4)
-	set_stack_mode  4 map4 1,2;;
+	set_stack_mode  4 map4 $SITES;;
 2x8)
-	set_stack_mode  8 map8 1,2;;
+	set_stack_mode  8 map8 $SITES;;
 4x8)
 	set_stack_mode 16 map8 1,2,3,4;;
 6x8)
