make mount usb stick retry .. may take time to load disk  On branch k414 	modified:   CARE/usb-stick

diff --git a/CARE/usb-stick b/CARE/usb-stick
--- a/CARE/usb-stick
+++ b/CARE/usb-stick
@@ -4,6 +4,15 @@ case $1 in
 mount|start)
 	[ -e /usbstick ] || mkdir /usbstick
 	[ -e /dev/sda1 ] || echo 1 > /sys/bus/usb/devices/1-1.1/bConfigurationValue
+	timeout=10
+	while [ ! -e /dev/sda1 ]; do
+		sleep 1
+		timeout=$(($timeout-1))
+		if [ $timeout -le 0 ]; then
+			echo "ERROR: timed out waiting for USB disk"
+			exit 1
+		fi	
+	done
 	mount /dev/sda1 /usbstick;;
 umount|stop)
 	sync;sync;umount /usbstick;;
